In [0]:
%matplotlib inline
import pandas as pd
import numpy as np
import gensim 
from gensim.models import word2vec
import gensim.downloader as api
import nltk
from scipy import spatial
from sklearn.manifold import TSNE
import re
import matplotlib.pyplot as plt

In [0]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [0]:
CORPUS = [
'the green car is fast',
'The blue car has low mileage',
'Your car has high mileage',
'I buy green shirt because it fits my blue eyes'
]


In [0]:
# Learn a word embedding from the corpus
# tokenize corpora
TOKENIZED_CORPUS = [nltk.word_tokenize(sentence) for sentence in CORPUS]
tokenized_new_doc = [nltk.word_tokenize(sentence) for sentence in new_doc]
# build the word2vec model on our training corpus
minimodel = gensim.models.Word2Vec(TOKENIZED_CORPUS, size=5, window=2, min_count=1)
print(minimodel['green'])
print(minimodel['blue'])

[0.02253218 0.04634771 0.02743567 0.07699963 0.09726954]
[ 0.05204004  0.03431813  0.04896523 -0.04637586  0.08097419]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [0]:
# Download pretrained word2vec Vectors
model = api.load("word2vec-google-news-300")

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [0]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [0]:
model.similarity("man","woman")

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


0.76640123

In [0]:
model.distance("man","woman") # distance = 1- similarity

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


0.2335987687110901

In [0]:
1 - spatial.distance.cosine(model['man'], model['woman'])

0.7664012312889099

In [0]:
print("The similarity between 'United_States' " + "and 'Canada':", model.similarity('United_States', 'Canada')) 
print("The similarity between 'United_States' " + "and 'Tunisia':", model.similarity('United_States', 'Tunisia')) 


The similarity between 'United_States' and 'Canada': 0.60190696
The similarity between 'United_States' and 'Tunisia': 0.24157229


/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [0]:
model.most_similar(positive=["king", "woman"], negative=["man"], topn=3)

In [0]:
model.most_similar(positive=['woman', 'doctor'], negative=['man'], topn=3)

In [0]:
model.most_similar(positive=['robots', 'future', 'humans'], topn=2)

In [0]:
model.doesnt_match("bank debt credit banana".split())