In [4]:
# import symbolic capability to Python
from sympy import *
# print things all pretty
from sympy.abc import *
from sympy.plotting import plot
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import display
init_printing()

$$ A = \begin{bmatrix}
1 & 2  \\
1 & 2 \\
1 & 2
\end{bmatrix} $$

In [9]:
rows = 3
columns = 2
A = np.matrix([[i for i in range(1, columns+1)] for _ in range(1, rows+1)])
A

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [19]:
A.shape

$$ B = \begin{bmatrix}
1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 
\end{bmatrix} $$

In [12]:
rows = 2
columns = 4
B = np.matrix([[i for i in range(1, columns+1)] for _ in range(1, rows+1)])
B

matrix([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [20]:
B.shape

Let assume $A$ is an $n × m$ matrix and $B$ is an $m × p$ matrix. Then the matrix product  
$$C = A B$$ is defined as 
$$c_{ij} = \sum_{k=1}^{m} a_{ik} b_{jk}$$
![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/470px-Matrix_multiplication_diagram_2.svg.png)

In [15]:
C = A @ B
C

matrix([[ 3,  6,  9, 12],
        [ 3,  6,  9, 12],
        [ 3,  6,  9, 12]])

In [21]:
C.shape

In [16]:
def dotproduct(A, B):
    number_of_rows = A.shape[0] 
    number_of_columns = B.shape[1] 
    C = np.zeros((number_of_rows, number_of_columns))
    for i in range(number_of_rows):
        for j in range(number_of_columns):
            cell_sum = 0
            for k in range(A.shape[1]):
                cell_sum += A[i, k] * B[k, j]
            C[i, j] = cell_sum
    return C

In [18]:
C = dotproduct(A, B)
C

array([[ 3.,  6.,  9., 12.],
       [ 3.,  6.,  9., 12.],
       [ 3.,  6.,  9., 12.]])

# Timing

In [26]:
rows = 100
columns = 200
A = np.matrix([[i for i in range(1, columns+1)] for _ in range(1, rows+1)])
A.shape

In [27]:
rows = 200
columns = 300
B = np.matrix([[i for i in range(1, columns+1)] for _ in range(1, rows+1)])
B.shape

In [28]:
%%timeit
C = A @ B

4.74 ms ± 497 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
%%timeit
C = dotproduct(A, B)

13.9 s ± 1.13 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
